---
- name: Playbook
  hosts: all
  tasks:
    - name: lookup secretsmanager secret in the current region using the nested feature
      debug: >
        msg="{{ lookup('aws_secret', 'awx-test.jojo-test', region='eu-central-1', aws_access_key="{{ AWS_ACCESS_KEY_ID }}", aws_secret_key="{{ AWS_SECRET_ACCESS_KEY }}", nested=true) }}"
