---
- name: Playbook
  hosts: all
  tasks:
    - name: lookup secretsmanager secret in the current region using the nested feature
      debug: >
        msg="{{ lookup('aws_secret', 'awx-test.jojo-test', region='eu-central-1', aws_profile='squirro-internal', nested=true) }}"
